config/routes.rb
Rails.application.routes.draw do
  resources :contents do
    resources :questions
  end

  resources :quizzes

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'contents#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :quiz_contents, dependent: :destroy
  has_many :quizzes, through: :quiz_contents, dependent: :destroy
  has_many :content_tags, dependent: :destroy
  has_many :tags, through: :content_tags
  belongs_to :user
  has_one_attached :file
  validates :file, attached: true, content_type: ['application/pdf'], size: { less_than: 10.megabytes, message: 'is not given between size' }
  validates :title, presence: true

  def summary
    return "#{self.title} (#{self.questions.count} #{'question'.pluralize(self.questions.count)})"
  end

  # this is the tag's list setter which will capture
  # params[:customer][:add_phone_numbers] when you submit the form
  def add_tags=(tag_string)
    self.tags = tag_string.split(" ").uniq.map do |tag|
      Tag.new(name: tag)
    end
  end

  # this will display tags in the text_field
  def add_tags
    tags.map { |t| t.name }.join(" ")
  end
end

app/models/content_tag.rb
class ContentTag < ApplicationRecord
  belongs_to :tag
  belongs_to :content
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :content
  validates :question, presence: true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :quiz_contents
  has_many :quiz_tags
  has_many :tags, through: :quiz_tags
  has_many :contents, through: :quiz_contents
  belongs_to :user
  validate :must_have_one_content_or_tag

  def must_have_one_content_or_tag
    if self.contents.empty? and self.tags.empty?
      errors.add(:quiz, 'You must select at least one piece of content or tag')
    end
  end
end

app/models/quiz_content.rb
class QuizContent < ApplicationRecord
  belongs_to :content
  belongs_to :quiz
end

app/models/quiz_tag.rb
class QuizTag < ApplicationRecord
  belongs_to :quiz
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :content_tags
  has_many :contents, through: :content_tags
  has_many :quiz_tags
  has_many :quizzes, through: :quiz_tags

  def summary
    return self.name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contents
  has_many :quizzes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
    if @contents.empty?
      flash.notice = 'Get started by adding some new content.'
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
    @content.user = current_user
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    @content.user = current_user

    respond_to do |format|
      if @content.save
        puts "RUN #{@content.id}"
        GenerateQuestionsJob.perform_later @content.id, :per_page
        format.html { redirect_to @content, notice: 'Your questions are being generated, please refresh the page in a few moments to see the question 🤩' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:title, :file, :add_tags)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:destroy]
  before_action :set_content, only: [:create, :destroy]

  # TODO: Refactor this
  # POST /questions
  # POST /questions.json
  def create
    GenerateQuestionsJob.perform_later params[:content_id], :random_page
    respond_to do |format|
      format.html { redirect_to @content, notice: 'A new question is being generated, please refresh the page in a few moments to see the question 🤩' }
      format.json { render :show, status: :created, location: @question }
    end
  end

  # TODO: Refactor this
  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to @content, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  def set_content
    @content = Content.find(params[:content_id])
  end

  # Only allow a list of trusted parameters through.
  def question_params
    params.require(:question).permit(:question)
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show]

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    questions_from_contents = @quiz.contents.map(&:questions).flatten
    questions_from_tags = @quiz.tags.map(&:contents).flatten.map(&:questions).flatten
    @questions = questions_from_contents.concat(questions_from_tags).uniq
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
    @quiz.user = current_user
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.user = current_user

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_quiz
    @quiz = Quiz.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def quiz_params
    params.require(:quiz).permit(content_ids: [], tag_ids: [])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content) do |form| %>
  <% if content.errors.any? %>
    <div class="alert">
      <h2 class="font-bold"><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul class="list-disc list-inside">
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: 'label' %>
    <%= form.text_field :title, class: 'text-field', placeholder: 'Enter a title for your content' %>
  </div>

  <div class="mb-4">
    <%= form.label 'Tags', class: 'label' %>
    <%= form.text_field :add_tags, class: 'text-field', placeholder: 'Enter a space separated list' %>
  </div>

  <% unless content.file.present? %>
    <div class="mb-4">
      <%= form.label :file, class: 'label' %>
      <%= form.file_field :file, class: 'file-input' %>
    </div>
  <% end %>

  <div class="flex flex-row space-x-4 justify-end items-center">
    <%= link_to 'Back', contents_path, class: 'secondary-button' %>
    <%= form.submit class: 'primary-button' %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1 class="text-3xl my-4">Editing Content</h1>

<%= render 'form', content: @content %>

app/views/contents/index.html.erb
<div class="flex items-center">
  <h1 class="heading-1 grow">My Content</h1>

  <div class="flex flex-row space-x-4 items-center justify-stretch">

    <%= link_to 'New Content', new_content_path, class: 'primary-button' %>

    <% if @contents.present? %>
      <%= link_to 'Quiz me', new_quiz_path, class: 'primary-button' %>
    <% end %>
  </div>
</div>

<div class="flex flex-col space-y-4 items-center">
  <% @contents.each do |content| %>
    <div class="flex flex-row items-center animated-card w-full group space-x-4">
      <%= link_to content, class: 'flex-1' do %>
        <div class="flex flex-row items-center space-x-4">
          <div class="flex-1 flex flex-col space-y-2">
            <h2 class="heading-2"><%= content.title %></h2>
            <p class="text-sm font-light">Number of Questions: <%= content.questions.count %></p>
          </div>
        </div>
      <% end %>
      <div class="flex flex-col items-end">
        <div class="flex flex-row space-x-4">
          <div class="invisible-until-group-hover min-w-[2rem]">
            <%= link_to edit_content_path(content) do %>
              <%= image_tag("edit.svg", class: 'button-icon') %>
            <% end %>
          </div>

          <%= button_to content,
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: 'invisible-until-group-hover' do %>
            <%= image_tag("delete.svg", class: 'button-icon') %>
          <% end %>
        </div>
        <div>
          <div class="flex flex-row space-x-2">
            <% content.tags.each do |tag| %>
              <div class="pill">
                <%= tag.name %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  <% end %>

  <% if @contents.empty? %>
    <div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 flex flex-col items-center">
      <%= image_tag("no_data.svg", width: 400, class: 'pt-32') %>
      <p class="pt-6 label">There's no content yet, upload a PDF to get started!</p>
    </div>
  <% end %>
</div>

app/views/contents/new.html.erb
<h1 class="text-3xl my-4">New Content</h1>

<div class="card">
  <%= render 'form', content: @content %>
</div>

app/views/contents/show.html.erb
<div class="space-y-4">
  <div class="h-full p-4">
    <%= link_to '← Back', contents_path, class: "text-md text-neutral-500" %>

    <div class="flex flex-row items-center">
      <div class="flex flex-col grow py-2 mb-4">
        <h1 class="heading-1 mb-2"><%= @content.title %></h1>
        <div class="flex flex-row space-x-2">
          <% @content.tags.each do |tag|  %>
            <div class="pill">
              <%= tag.name %>
            </div>
          <% end %>
        </div>
      </div>
      <%= button_to 'Quiz me',
                    quizzes_path,
                    method: :post,
                    data: { confirm: 'Ready to answer some questions?' },
                    params: { quiz: { content_ids: [@content.id] } },
                    class: 'primary-button' %>
    </div>

    <div class="flex justify-center items-center w-full h-[65vh]">
      <iframe src="<%= url_for(@content.file) %>" width="100%" height="100%"></iframe>
    </div>
    <div class="flex flex-row items-center">
      <div class="grow mb-8 mt-10">
        <h1 class="heading-1 inline">Questions</h1>
        <% if @content.questions.count > 0 %>
          <span class="pl-4 text-neutral-500">(<%= pluralize(@content.questions.count, 'question') %>)</span>
        <% end %>
      </div>
      <%= button_to "Add Question", content_questions_path(@content), method: :post, class: "primary-button" %>
    </div>
    <div class="flex flex-col justify-center items-center">
      <ul class="flex flex-col space-y-4 w-full list-decimal list-inside mb-4">
        <% @content.questions.each_with_index do |question, i| %>
          <li class="card flex flex-row group">
            <span class="mr-2"><%= i + 1 %>.</span>
            <ul class="inline-block grow">
              <li><b>Q: </b><%= question.question %></li>
              <li><b>A: </b><%= question.answer %></li>
            </ul>
            <div class="self-center min-w-[2rem]">
              <%= button_to content_question_path(@content, question),
                            method: :delete,
                            data: { confirm: 'Are you sure?' },
                            class: 'invisible-until-group-hover' do %>
                <%= image_tag("delete.svg", class: 'button-icon') %>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="w-full bg-neutral-50 drop-shadow-md p-4 flex sticky top-0 z-50">
  <div class="grow">
    <%= link_to '/' do %>
      <%= image_tag("logo-with-text.svg", class: 'inline-block max-h-8 mr-2', alt: 'StudyBuddy Logo') %>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudyBuddy</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-neutral-100 w-full h-full">

<%= render "layouts/header" %>

<main class="container mx-auto my-8 px-5 flex flex-col h-full">
  <% if notice %>
    <p id="notice" class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p id="alert" class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>
</main>

</body>
</html>

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz) do |form| %>
  <% if quiz.errors.any? %>
    <div class="alert">
      <h2 class="font-bold"><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul class="list-disc list-inside">
        <% quiz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4 grid grid-cols-2 pr-32">
    <div class="flex flex-col">
      <%= form.label 'Content', class: 'label' %>
      <%= form.collection_check_boxes :content_ids, current_user.contents.all, :id, :summary do |content| %>
        <div class="flex flex-row items-center space-x-4">
          <%= content.check_box class: 'checkbox' %>
          <%= content.label %>
        </div>
      <% end %>
    </div>

    <div class="flex flex-col">
      <%= form.label 'Tags', class: 'label' %>
      <div class="flex flex-col">
        <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :summary do |content| %>
          <div class="flex flex-row items-center space-x-4">
            <%= content.check_box class: 'checkbox' %>
            <%= content.label %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="flex flex-row space-x-4 justify-end items-center">
    <%= link_to 'Back', contents_path, class: 'secondary-button' %>
    <%= form.submit class: 'primary-button' %>
  </div>
<% end %>

app/views/quizzes/new.html.erb
<h1 class="text-3xl my-4">New Quiz</h1>

<div class="card">
  <%= render 'form', quiz: @quiz %>
</div>

app/views/quizzes/show.html.erb
<%= link_to '← Back', contents_path, class: "text-md text-neutral-500" %>
<h1 class="heading-1">Your Quiz</h1>
<ul class="flex flex-col space-y-4 w-full list-decimal list-inside">
  <% @questions.shuffle.each_with_index do |question, i| %>
      <li class="card flex flex-row quiz-card" id="<%= i + 1 %>">
        <span class="mr-2"><%= i + 1 %>.</span>
        <ul class="inline-block">
          <li><b>Q: </b><%= question.question %></li>
          <li>
            <b>A: </b>
            <span class="hint">&lt;Click to reveal...&gt;</span>
            <span class="answer hidden"><%= question.answer %></span></li>
        </ul>
      </li>
  <% end %>
</ul>